### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by samuk** [Ategon/Lemmy-Mega-Bot#3]
Have I put something stupid in .env?

~/Downloads/Lemmy-Mega-Bot-main$ node main.js
STARTED: Started Bot
INSTANCES: 1 instances loaded.
FEEDS: 1 feeds loaded.
/home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/lemmy-bot/dist/helpers.js:36
const stripPort = (instance) => instance.replace(/:.*/, '');
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at stripPort (/home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/lemmy-bot/dist/helpers.js:36:42)
    at /home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/lemmy-bot/dist/bot.js:336:141
    at Array.some (<anonymous>)
    at new LemmyBot (/home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/lemmy-bot/dist/bot.js:336:99)
    at file:///home/sam/Downloads/Lemmy-Mega-Bot-main/main.js:97:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0

**Comment by Ategon** [comment]
Looks like an issue with getting the instance name filled in properly when the bot tries to log in. If you go into main.js and replace process.env.INSTANCE with the instance name in quotation marks (e.g. "programming.dev") does it work / give you a different error? Dont know for sure how you formatted your .env file but this should see if thats the issue (it probably will throw a similar one for the username or password)

**Comment by samuk** [comment]
Thanks. That does give a new error

$ node main.js
STARTED: Started Bot
INSTANCES: 1 instances loaded.
FEEDS: 1 feeds loaded.
Starting bot
Initializing DB
logging in
DB: Connected to the database.
TABLE: Loaded posts table.
POSTS: 0 posts in database.
TABLE: Loaded time table

/home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/node-fetch/lib/index.js:1505
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://lemmy.world/api/v3/user/login failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/sam/Downloads/Lemmy-Mega-Bot-main/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

Node.js v18.13.0

**Comment by Ategon** [comment]
Alright and that looks like one for logging in so just do the same with process.env.USERNAME and process.env.PASSWORD replacing with your username and password respectively and it should be fixed

**Comment by samuk** [comment]
Great thanks. I'll close this as the initial issue is resolved. I'll try a few more times. I know lemmy.world has been having DDOS attacks so I wonder if it's related to that?

**Comment by samuk** [comment]
That gets me logged in OK. This is where I'm trying to post https://lemmy.world/c/climate@kbin.social I can't get the syntax correct.


:~/Downloads/Lemmy-Mega-Bot-main$ node main.js
STARTED: Started Bot
INSTANCES: 1 instances loaded.
FEEDS: 1 feeds loaded.
Starting bot
Initializing DB
logging in
DB: Connected to the database.
TABLE: Loaded posts table.
POSTS: 0 posts in database.
TABLE: Loaded time table
logged in
Could not get !climate@kbin.social@lemmy.world

**Comment by Ategon** [comment]
Are you entering that as the community id in createPost? Community id is a random number that you cant really find easily manually but theres another function to get it called getCommunityId. 

Usually I do something like
const communityId = await getCommunityId({ name: 'climate', instance: 'kbin.social' })
await createPost({ name: 'Test', body: 'test', community_id: communityId})

Have not tested how it functions with kbin though, may not work as thats a completely different platform

**Comment by samuk** [comment]
Nice that seems to work now. Thanks

**Comment by Ategon** [comment]
Theres not currently a way to limit the URLS but if thats being thrown when youre creating comments you can adjust the sleepDuration variable in main. Ill add that in real quick though

And yeah some rss feeds to some funky stuff in some of the parts. Dont think it provides the actual link anywhere. For getting the html tags out I can push out an update to handle that

**Comment by Ategon** [comment]
I just pushed some changes to the bot that should fix most things. Let me know if something still doesnt work
